Test against Python 3.11, windows and update github actions.
karlicoss/orgparse pull request #61
Opened 2022-11-29 18:37 UTC by krisfremen

At first I just wanted to get Python 3.11 to be tested, but I saw some TODO items and warnings in the github actions, so a few changes in this PR:

- Added Python 3.11
- Pinned Python 3.6 to ubuntu20.04
- Added Windows
- Updated versions of github actions

Cheers!

2022-12-06 22:55 UTC, karlicoss requested changes
thank you, very appreciated! Looks good, just a few comments

2022-12-06 22:55 UTC, karlicoss commented on setup.py
> +        setup_requires=['setuptools_scm==6.4.2'],
hmm, why are you pinning it out of curiosity?

2022-12-06 22:55 UTC, karlicoss commented on .github/workflows/main.yml
> +      run: echo "$HOME/Library/Python/${{ matrix.python-version }}/bin" >> $GITHUB_PATH
oh interesting, is that necessary for macos and 3.11 now? good to know for my other projects -- haven't started using 3.11 yet

2022-12-06 22:55 UTC, karlicoss commented on .github/workflows/main.yml
> +        include: [{platform: ubuntu-20.04, python-version: '3.6'}]
Thanks! but tbh, I've been dropping 3.6 support since it's reached end of life a while ago. So might be easiest just to do that here?

2022-12-07 01:51 UTC, krisfremen commented on .github/workflows/main.yml
> +      run: echo "$HOME/Library/Python/${{ matrix.python-version }}/bin" >> $GITHUB_PATH
yes, I'm not sure if it's something that the github action isn't doing or something has changed for 3.11 specifically, but it's not adding the PATH for it.

2022-12-07 02:16 UTC, krisfremen commented on .github/workflows/main.yml
> +        include: [{platform: ubuntu-20.04, python-version: '3.6'}]
sounds good, I just pushed up a commit to drop it.

2022-12-07 02:17 UTC, krisfremen commented on setup.py
> +        setup_requires=['setuptools_scm==6.4.2'],
3.6 has to use that version to fully build, 3.7 and above builds fine without the pin though.

2022-12-07 02:24 UTC, merged

2022-12-07 02:24 UTC, karlicoss commented
thank you!

2023-10-04 19:42 UTC, karlicoss commented on .github/workflows/main.yml
> +      run: echo "$HOME/Library/Python/${{ matrix.python-version }}/bin" >> $GITHUB_PATH
Looks like it's not necessary anymore, works without it! https://github.com/karlicoss/orgparse/pull/66